name: Build

on: [push]

jobs:
  build:
    name: Build ASP.NET app
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: dotnet build
        run: dotnet build